swagger: '2.0'
info:
  version: 1.0.0
  title: MediaWiki API
schemes:
  - https
paths:
  /w/api.php:
    get:
      produces:
        - application/json
      parameters:
        - name: action
          in: query
          required: true
          type: string
        - name: format
          in: query
          required: true
          type: string
        - name: meta
          in: query
          required: true
          type: string
        - name: type
          in: query
          required: true
          type: string
      responses:
        '200':
          description: result list
          schema:
            $ref: '#/definitions/Result'
definitions:
  Result:
    type: object
    properties:
      query:
        $ref: '#/definitions/Query'
  Query:
    type: object
    properties:
      tokens:
        $ref: '#/definitions/Tokens'
  Tokens:
    type: object
    properties:
      logintoken:
        type: string
