//
// DeviceEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class DeviceEntity: Codable {

    public enum Status: String, Codable { 
        case using = "using"
        case free = "free"
    }
    public var userName: String?
    public var mailAddress: String?
    public var deviceName: String?
    public var deviceId: String?
    public var returnDate: Date?
    public var status: Status?


    public init(userName: String?=nil, mailAddress: String?=nil, deviceName: String?=nil, deviceId: String?=nil, returnDate: Date?=nil, status: Status?=nil) {
        self.userName = userName
        self.mailAddress = mailAddress
        self.deviceName = deviceName
        self.deviceId = deviceId
        self.returnDate = returnDate
        self.status = status
    }
}
