//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class DefaultAPI {
    /**

     - parameter action: (query)  
     - parameter format: (query)  
     - parameter meta: (query)  
     - parameter type: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func wApiPhpGet(action: String, format: String, meta: String, type: String, completion: @escaping ((_ data: Result?,_ error: Error?) -> Void)) {
        wApiPhpGetWithRequestBuilder(action: action, format: format, meta: meta, type: type).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**

     - parameter action: (query)  
     - parameter format: (query)  
     - parameter meta: (query)  
     - parameter type: (query)  
     - returns: Observable<Result>
     */
    open class func wApiPhpGet(action: String, format: String, meta: String, type: String) -> Observable<Result> {
        return Observable.create { observer -> Disposable in
            wApiPhpGet(action: action, format: format, meta: meta, type: type) { data, error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     - GET /w/api.php
     - examples: [{contentType=application/json, example={
  "query" : {
    "tokens" : {
      "logintoken" : "logintoken"
    }
  }
}}]
     
     - parameter action: (query)  
     - parameter format: (query)  
     - parameter meta: (query)  
     - parameter type: (query)  

     - returns: RequestBuilder<Result> 
     */
    open class func wApiPhpGetWithRequestBuilder(action: String, format: String, meta: String, type: String) -> RequestBuilder<Result> {
        let path = "/w/api.php"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "action": action, 
            "format": format, 
            "meta": meta, 
            "type": type
        ])
        

        let requestBuilder: RequestBuilder<Result>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
